### ISSUE TITLE
Could not load "libgroovyBC.so"

### ISSUE THREAD

**Issue by lilux618** [TS-CUBED/haemoFoam#30]
I compiled the solver by running "Allwmake".  When running the tutorial, it shows that Could not load "libgroovyBC.so" and then give the error like follow:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/60692776/189871913-07eb820d-d45f-48c9-8a16-1e428cab3a36.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/60692776/189871995-6d84587b-2d94-4ea5-a8b1-ea2306593f30.png">
What's wrong with me ?

**Comment by TS-CUBED** [comment]
Nothing. You just need to install swak4Foam if you want to use groovyBC.

GroovyBC is not part of haemoFoam but comes with swak4Foam.
________________________________
From: lilux618 ***@***.***>
Sent: Tuesday, September 13, 2022 10:57:42 AM
To: TS-CUBED/haemoFoam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TS-CUBED/haemoFoam] Could not load "libgroovyBC.so" (Issue #30)


CAUTION: This message was sent from outside the University, purportedly from ***@***.*** .

Please check the sender is legitimate before responding. Please treat any links or attachments with care -  do not follow or open them unless you are sure they are genuine.



I compiled the solver by running "Allwmake". When running the tutorial, it shows that Could not load "libgroovyBC.so" and then give the error like follow:
[image]<https://user-images.githubusercontent.com/60692776/189871913-07eb820d-d45f-48c9-8a16-1e428cab3a36.png>
[image]<https://user-images.githubusercontent.com/60692776/189871995-6d84587b-2d94-4ea5-a8b1-ea2306593f30.png>
What's wrong with me ?
